import { NumberMaker, Typer } from "../types";
export declare const uint8: Typer<number>;
export declare const uint16: Typer<number>;
export declare const uint32: Typer<number>;
export declare const bigUint64: Typer<bigint>;
export declare const int8: Typer<number>;
export declare const int16: Typer<number>;
export declare const int32: Typer<number>;
export declare const bigInt64: Typer<bigint>;
export declare const float32: Typer<number>;
export declare const float64: Typer<number>;
export declare const number: NumberMaker;
